export type Applicant = {
  id: number;
  name: string;
  gender: string;
  age: number;
  education: string;
  skills: string;
  employmentStatus: string;
  contactNumber: string;
  email: string;
  address: string;
  civilStatus?: string;
  hasDisability?: boolean;
  isOFW?: boolean;
  isFormerOFW?: boolean;
  is4PsBeneficiary?: boolean;
  jobPreference?: string;
  language?: string;
  fullFormData?: Record<string, unknown>;
};

export const SEED: Applicant[] = [
  {
    id: 1,
    name: "Maria Santos",
    gender: "Female",
    age: 28,
    education: "Bachelor of Science in Nursing (Tertiary)",
    skills: "Caregiving, Healthcare, Patient Assessment",
    employmentStatus: "Unemployed",
    contactNumber: "09171234567",
    email: "maria.santos@email.com",
    address: "Brgy. Maloro, Tangub City",
    civilStatus: "Single",
    hasDisability: false,
    isOFW: false,
    isFormerOFW: false,
    is4PsBeneficiary: false,
    jobPreference: "Healthcare",
    language: "Filipino",
    fullFormData: {
      firstName: "Maria",
      middleName: "Cruz",
      surname: "Santos",
      suffix: "",
      dateOfBirth: "1998-05-10",
      sex: "Female",
      religion: "Roman Catholic",
      civilStatus: "Single",
      height: "5'4\"",
      houseNo: "Blk 3",
      barangay: "Maloro",
      municipality: "Tangub City",
      province: "Misamis Occidental",
      contactNumber: "09171234567",
      email: "maria.santos@email.com",
      tin: "",
      isOFW: "No",
      ofwCountry: "",
      isFormerOFW: "No",
      formerOFWCountry: "",
      formerOFWReturnDate: "",
      is4PsBeneficiary: "No",
      householdIdNo: "",
      hasDisability: [],
      disabilityOther: "",
      currentlyInSchool: "No",
      elementary: {
        schoolName: "Maloro Elementary School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        graduated: "Yes",
        yearGraduated: "2010",
        levelReached: "",
        yearLastAttended: "2010",
      },
      secondary: {
        schoolName: "Tangub City National High School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        type: "Public",
        seniorHighStrand: "HUMSS",
        graduated: "Yes",
        yearGraduated: "2016",
        levelReached: "",
        yearLastAttended: "2016",
      },
      tertiary: {
        schoolName: "Misamis University",
        schoolCity: "Ozamiz City",
        schoolProvince: "Misamis Occidental",
        course: "Bachelor of Science in Nursing",
        graduated: "Yes",
        yearGraduated: "2020",
        levelReached: "",
        yearLastAttended: "2020",
      },
      graduateStudies: [],
      trainings: [
        {
          course: "Basic Life Support & CPR",
          hoursOfTraining: "16",
          institution: "Philippine Red Cross",
          skillsAcquired: "CPR, First Aid",
          certificateReceived: "Yes",
        },
      ],
      eligibilities: [],
      professionalLicenses: [],
      workExperiences: [
        {
          companyName: "Tangub City Rural Health Unit",
          position: "Community Health Nurse",
          from: "2021-01",
          to: "2023-06",
          status: "Regular",
        },
      ],
      otherSkills: ["Caregiving", "Healthcare", "Patient Assessment", "Vital Signs Monitoring"],
      otherSkillsSpecify: [],
      jobPreferences: [
        {
          occupation: "Nurse",
          employmentType: ["Regular", "Part-time"],
          workLocation: ["Local", "Abroad"],
        },
      ],
      languages: [
        { language: "Filipino", read: true, write: true, speak: true, understand: true },
        { language: "English", read: true, write: true, speak: true, understand: true },
        { language: "Bisaya", read: false, write: false, speak: true, understand: true },
      ],
      referredProgram: "",
      cdspPrograms: [],
      projectIdNumber: "",
      projectLocation: "",
      projectRegion: "",
      projectCity: "",
      projectDetails: { type: [], programComponent: [], wayOfImplementation: [], nameOfProject: "" },
      pagIbigNo: "",
      philHealthNo: "",
      sssNo: "",
      otherProgramName: "",
      otherProgramNo: "",
    },
  },
  {
    id: 2,
    name: "Juan Santos Dela Cruz",
    gender: "Male",
    age: 27,
    education: "Bachelor of Science in Accountancy (Tertiary)",
    skills: "Accounting, MS Excel, Bookkeeping, QuickBooks, Financial Analysis",
    employmentStatus: "Unemployed",
    contactNumber: "09171234567",
    email: "juan.delacruz@gmail.com",
    address: "P-4, Mantic, Tangub City",
    civilStatus: "Single",
    hasDisability: false,
    isOFW: false,
    isFormerOFW: false,
    is4PsBeneficiary: false,
    jobPreference: "Accounting",
    language: "Filipino",
    fullFormData: {
      firstName: "Juan",
      middleName: "Santos",
      surname: "Dela Cruz",
      suffix: "",
      dateOfBirth: "1999-03-15",
      sex: "Male",
      religion: "Roman Catholic",
      civilStatus: "Single",
      height: "5'7\"",
      houseNo: "P-4",
      barangay: "Mantic",
      municipality: "Tangub City",
      province: "Misamis Occidental",
      contactNumber: "09171234567",
      email: "juan.delacruz@gmail.com",
      tin: "",
      isOFW: "No",
      ofwCountry: "",
      isFormerOFW: "No",
      formerOFWCountry: "",
      formerOFWReturnDate: "",
      is4PsBeneficiary: "No",
      householdIdNo: "",
      hasDisability: [],
      disabilityOther: "",
      currentlyInSchool: "No",
      elementary: {
        schoolName: "Mantic Elementary School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        graduated: "Yes",
        yearGraduated: "2013",
        levelReached: "",
        yearLastAttended: "2013",
      },
      secondary: {
        schoolName: "Tangub City National High School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        type: "Public",
        seniorHighStrand: "ABM",
        graduated: "Yes",
        yearGraduated: "2019",
        levelReached: "",
        yearLastAttended: "2019",
      },
      tertiary: {
        schoolName: "Misamis University",
        schoolCity: "Ozamiz City",
        schoolProvince: "Misamis Occidental",
        course: "Bachelor of Science in Accountancy",
        graduated: "Yes",
        yearGraduated: "2023",
        levelReached: "",
        yearLastAttended: "2023",
      },
      graduateStudies: [],
      trainings: [],
      eligibilities: [],
      professionalLicenses: [],
      workExperiences: [
        {
          companyName: "Tangub City Local Government Unit",
          position: "Accounting Staff",
          from: "2023-01",
          to: "2024-06",
          status: "Regular",
        },
      ],
      otherSkills: ["Accounting", "MS Excel", "Bookkeeping", "QuickBooks", "Financial Analysis"],
      otherSkillsSpecify: [],
      jobPreferences: [
        {
          occupation: "Accountant",
          employmentType: ["Regular"],
          workLocation: ["Local"],
        },
      ],
      languages: [
        { language: "Filipino", read: true, write: true, speak: true, understand: true },
        { language: "English", read: true, write: true, speak: true, understand: true },
      ],
      referredProgram: "",
      cdspPrograms: [],
      projectIdNumber: "",
      projectLocation: "",
      projectRegion: "",
      projectCity: "",
      projectDetails: { type: [], programComponent: [], wayOfImplementation: [], nameOfProject: "" },
      pagIbigNo: "",
      philHealthNo: "",
      sssNo: "",
      otherProgramName: "",
      otherProgramNo: "",
    },
  },
  {
    id: 3,
    name: "Ana Reyes",
    gender: "Female",
    age: 22,
    education: "Senior High School Graduate",
    skills: "Cooking, Customer Service",
    employmentStatus: "Unemployed",
    contactNumber: "09351112233",
    email: "ana.reyes@email.com",
    address: "Brgy. Bocator, Tangub City",
    civilStatus: "Single",
    hasDisability: false,
    isOFW: false,
    isFormerOFW: false,
    is4PsBeneficiary: true,
    jobPreference: "Service Industry",
    language: "Filipino",
    fullFormData: {
      firstName: "Ana",
      middleName: "Lim",
      surname: "Reyes",
      suffix: "",
      dateOfBirth: "2004-08-22",
      sex: "Female",
      religion: "Roman Catholic",
      civilStatus: "Single",
      height: "5'2\"",
      houseNo: "Blk 5",
      barangay: "Bocator",
      municipality: "Tangub City",
      province: "Misamis Occidental",
      contactNumber: "09351112233",
      email: "ana.reyes@email.com",
      tin: "",
      isOFW: "No",
      ofwCountry: "",
      isFormerOFW: "No",
      formerOFWCountry: "",
      formerOFWReturnDate: "",
      is4PsBeneficiary: "Yes",
      householdIdNo: "4PS-2024-00123",
      hasDisability: [],
      disabilityOther: "",
      currentlyInSchool: "No",
      elementary: {
        schoolName: "Bocator Elementary School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        graduated: "Yes",
        yearGraduated: "2016",
        levelReached: "",
        yearLastAttended: "2016",
      },
      secondary: {
        schoolName: "Tangub City National High School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        type: "Public",
        seniorHighStrand: "TVL",
        graduated: "Yes",
        yearGraduated: "2022",
        levelReached: "",
        yearLastAttended: "2022",
      },
      tertiary: {
        schoolName: "",
        schoolCity: "",
        schoolProvince: "",
        course: "",
        graduated: "No",
        yearGraduated: "",
        levelReached: "",
        yearLastAttended: "",
      },
      graduateStudies: [],
      trainings: [
        {
          course: "Food and Beverage Services NCII",
          hoursOfTraining: "80",
          institution: "TESDA Tangub City",
          skillsAcquired: "Food Service, Customer Relations",
          certificateReceived: "Yes",
        },
      ],
      eligibilities: [],
      professionalLicenses: [],
      workExperiences: [],
      otherSkills: ["Cooking", "Customer Service", "Food Preparation", "Barista"],
      otherSkillsSpecify: [],
      jobPreferences: [
        {
          occupation: "Food Service Worker",
          employmentType: ["Regular", "Part-time"],
          workLocation: ["Local"],
        },
      ],
      languages: [
        { language: "Filipino", read: true, write: true, speak: true, understand: true },
        { language: "Bisaya", read: false, write: false, speak: true, understand: true },
      ],
      referredProgram: "",
      cdspPrograms: [],
      projectIdNumber: "",
      projectLocation: "",
      projectRegion: "",
      projectCity: "",
      projectDetails: { type: [], programComponent: [], wayOfImplementation: [], nameOfProject: "" },
      pagIbigNo: "",
      philHealthNo: "",
      sssNo: "",
      otherProgramName: "",
      otherProgramNo: "",
    },
  },
  {
    id: 4,
    name: "Roberto Manalo",
    gender: "Male",
    age: 45,
    education: "Bachelor of Science in Information Technology (Tertiary)",
    skills: "IT / Technology, Computer Literacy, Network Administration",
    employmentStatus: "Employed",
    contactNumber: "09456667788",
    email: "roberto.manalo@email.com",
    address: "Brgy. San Pablo, Tangub City",
    civilStatus: "Married",
    hasDisability: true,
    isOFW: false,
    isFormerOFW: false,
    is4PsBeneficiary: false,
    jobPreference: "IT / Technology",
    language: "English",
    fullFormData: {
      firstName: "Roberto",
      middleName: "Garcia",
      surname: "Manalo",
      suffix: "",
      dateOfBirth: "1981-11-03",
      sex: "Male",
      religion: "Roman Catholic",
      civilStatus: "Married",
      height: "5'9\"",
      houseNo: "123",
      barangay: "San Pablo",
      municipality: "Tangub City",
      province: "Misamis Occidental",
      contactNumber: "09456667788",
      email: "roberto.manalo@email.com",
      tin: "",
      isOFW: "No",
      ofwCountry: "",
      isFormerOFW: "No",
      formerOFWCountry: "",
      formerOFWReturnDate: "",
      is4PsBeneficiary: "No",
      householdIdNo: "",
      hasDisability: ["Visual Disability"],
      disabilityOther: "",
      currentlyInSchool: "No",
      elementary: {
        schoolName: "San Pablo Elementary School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        graduated: "Yes",
        yearGraduated: "1993",
        levelReached: "",
        yearLastAttended: "1993",
      },
      secondary: {
        schoolName: "Tangub City National High School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        type: "Public",
        seniorHighStrand: "",
        graduated: "Yes",
        yearGraduated: "1997",
        levelReached: "",
        yearLastAttended: "1997",
      },
      tertiary: {
        schoolName: "Capitol University",
        schoolCity: "Cagayan de Oro",
        schoolProvince: "Misamis Oriental",
        course: "Bachelor of Science in Information Technology",
        graduated: "Yes",
        yearGraduated: "2001",
        levelReached: "",
        yearLastAttended: "2001",
      },
      graduateStudies: [],
      trainings: [
        {
          course: "Cisco Certified Network Associate (CCNA)",
          hoursOfTraining: "120",
          institution: "Cisco Networking Academy",
          skillsAcquired: "Network Configuration, Routing, Switching",
          certificateReceived: "Yes",
        },
      ],
      eligibilities: [],
      professionalLicenses: [],
      workExperiences: [
        {
          companyName: "DOST Regional Office X",
          position: "IT Support Specialist",
          from: "2015-06",
          to: "Present",
          status: "Regular",
        },
        {
          companyName: "Tangub City Hall",
          position: "Systems Administrator",
          from: "2003-01",
          to: "2015-05",
          status: "Regular",
        },
      ],
      otherSkills: ["Network Administration", "IT Support", "Computer Literacy", "Web Development", "Database Management"],
      otherSkillsSpecify: [],
      jobPreferences: [
        {
          occupation: "IT Manager",
          employmentType: ["Regular"],
          workLocation: ["Local"],
        },
      ],
      languages: [
        { language: "English", read: true, write: true, speak: true, understand: true },
        { language: "Filipino", read: true, write: true, speak: true, understand: true },
      ],
      referredProgram: "",
      cdspPrograms: [],
      projectIdNumber: "",
      projectLocation: "",
      projectRegion: "",
      projectCity: "",
      projectDetails: { type: [], programComponent: [], wayOfImplementation: [], nameOfProject: "" },
      pagIbigNo: "",
      philHealthNo: "",
      sssNo: "",
      otherProgramName: "",
      otherProgramNo: "",
    },
  },
  {
    id: 5,
    name: "Ligaya Flores",
    gender: "Female",
    age: 31,
    education: "Bachelor of Science in Nursing (Tertiary)",
    skills: "Caregiving, Healthcare",
    employmentStatus: "Unemployed",
    contactNumber: "09561234000",
    email: "ligaya.flores@email.com",
    address: "Brgy. Hoyohoy, Tangub City",
    civilStatus: "Widowed",
    hasDisability: false,
    isOFW: true,
    isFormerOFW: false,
    is4PsBeneficiary: false,
    jobPreference: "Healthcare",
    language: "Filipino",
    fullFormData: {
      firstName: "Ligaya",
      middleName: "Bautista",
      surname: "Flores",
      suffix: "",
      dateOfBirth: "1995-02-14",
      sex: "Female",
      religion: "Roman Catholic",
      civilStatus: "Widowed",
      height: "5'3\"",
      houseNo: "56",
      barangay: "Hoyohoy",
      municipality: "Tangub City",
      province: "Misamis Occidental",
      contactNumber: "09561234000",
      email: "ligaya.flores@email.com",
      tin: "",
      isOFW: "Yes",
      ofwCountry: "Saudi Arabia",
      isFormerOFW: "No",
      formerOFWCountry: "",
      formerOFWReturnDate: "",
      is4PsBeneficiary: "No",
      householdIdNo: "",
      hasDisability: [],
      disabilityOther: "",
      currentlyInSchool: "No",
      elementary: {
        schoolName: "Hoyohoy Elementary School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        graduated: "Yes",
        yearGraduated: "2007",
        levelReached: "",
        yearLastAttended: "2007",
      },
      secondary: {
        schoolName: "Tangub City National High School",
        schoolCity: "Tangub City",
        schoolProvince: "Misamis Occidental",
        type: "Public",
        seniorHighStrand: "",
        graduated: "Yes",
        yearGraduated: "2013",
        levelReached: "",
        yearLastAttended: "2013",
      },
      tertiary: {
        schoolName: "Misamis University",
        schoolCity: "Ozamiz City",
        schoolProvince: "Misamis Occidental",
        course: "Bachelor of Science in Nursing",
        graduated: "Yes",
        yearGraduated: "2017",
        levelReached: "",
        yearLastAttended: "2017",
      },
      graduateStudies: [],
      trainings: [
        {
          course: "Elderly Care Management",
          hoursOfTraining: "40",
          institution: "TESDA",
          skillsAcquired: "Geriatric Care, Medication Administration",
          certificateReceived: "Yes",
        },
      ],
      eligibilities: [],
      professionalLicenses: [],
      workExperiences: [
        {
          companyName: "King Fahad Medical City",
          position: "Staff Nurse",
          from: "2019-03",
          to: "Present",
          status: "Regular",
        },
      ],
      otherSkills: ["Caregiving", "Healthcare", "Patient Care", "Medication Administration", "Wound Care"],
      otherSkillsSpecify: [],
      jobPreferences: [
        {
          occupation: "Registered Nurse",
          employmentType: ["Regular"],
          workLocation: ["Abroad"],
        },
      ],
      languages: [
        { language: "Filipino", read: true, write: true, speak: true, understand: true },
        { language: "English", read: true, write: true, speak: true, understand: true },
        { language: "Arabic", read: false, write: false, speak: false, understand: true },
      ],
      referredProgram: "",
      cdspPrograms: [],
      projectIdNumber: "",
      projectLocation: "",
      projectRegion: "",
      projectCity: "",
      projectDetails: { type: [], programComponent: [], wayOfImplementation: [], nameOfProject: "" },
      pagIbigNo: "",
      philHealthNo: "",
      sssNo: "",
      otherProgramName: "",
      otherProgramNo: "",
    },
  },
];
