// Generates the General PESO Report's Excel export by patching a template
// workbook that contains two REAL native Excel charts — authored by hand in
// real Microsoft Excel (Insert > Chart), not generated by a library. An
// earlier version of this template was built with openpyxl, but Excel's own
// file-open validator rejected it ("Removed Part: drawing1.xml") even though
// it was schema-legal enough for other readers — openpyxl's chart XML just
// isn't reliably Excel-safe. Only real Excel can be trusted to write chart
// XML Excel itself will always accept.
//
// This patches the .xlsx zip directly (JSZip) rather than round-tripping
// through ExcelJS, which has no API for native chart objects at all (it can
// only embed static images) — same technique pesoMonthlyReport.ts uses for
// the official PESO/LMI report's charts.
import JSZip from 'jszip'
import { GENERAL_PESO_PROGRAM_COLORS } from './generalPesoColors'
import type { GeneralPesoProgramRow } from '../../services/reportService'

const templateUrl = new URL('./general_peso_template.xlsx', import.meta.url).href

const SHEET_CHARTDATA = 'xl/worksheets/sheet1.xml'
const SHEET_REPORT = 'xl/worksheets/sheet2.xml'
const SHEET_DETAILS = 'xl/worksheets/sheet3.xml'
const CHART_BAR = 'xl/charts/chart1.xml'
const CHART_PIE = 'xl/charts/chart2.xml'
const MAX_PROGRAMS = 7 // the template pre-allocates rows 2..8 (matches the 7 selectable programs)

const xmlEsc = (s: unknown) =>
  String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

// Replace one cell's value in a worksheet XML, PRESERVING its style (s attr).
// Same approach as pesoMonthlyReport.ts's setCell. The template's text cells
// use shared strings (t="s", real Excel wrote them that way) but overwriting
// with a self-contained inline string is equally valid OOXML and is exactly
// what pesoMonthlyReport.ts already does against its own real-Excel template.
function setCell(xml: string, ref: string, value: string | number, isNumber: boolean): string {
  const re = new RegExp(`<c r="${ref}"([^>]*?)(?:/>|>.*?</c>)`, 's')
  if (!re.test(xml)) throw new Error(`General PESO template: cell ${ref} not found`)
  const inner = isNumber
    ? `><v>${value}</v></c>`
    : ` t="inlineStr"><is><t xml:space="preserve">${xmlEsc(value)}</t></is></c>`
  return xml.replace(re, (_m, attrs: string) => `<c r="${ref}"${attrs.replace(/\s*t="[^"]*"/, '')}${inner}`)
}

// Shrinks ChartData!$A$2:$A$8 -> ChartData!$A$2:$A$(1+N) (and the same for
// column B) in a chart's <c:cat>/<c:val> <c:f> references, so the category
// axis reflects exactly the selected programs — not a fixed 7 slots with
// zeroed rows.
function setChartRange(chartXml: string, lastRow: number): string {
  return chartXml.replace(/(ChartData!\$([A-Z])\$2:\$\2\$)\d+/g, `$1${lastRow}`)
}

// Rebuilds a <c:strCache> (category labels) or <c:numCache> (values) block to
// match exactly N points — real Excel bakes these caches in (unlike a
// library-generated chart with no cache at all), so they must be kept in sync
// with the shrunk <c:f> range or the chart shows stale/mismatched data until
// a manual recalculation.
function setStrCache(chartXml: string, values: string[]): string {
  return chartXml.replace(/(<c:cat><c:strRef><c:f>[^<]*<\/c:f><c:strCache>).*?(<\/c:strCache>)/s, (_m, pre: string, post: string) => {
    const pts = values.map((v, i) => `<c:pt idx="${i}"><c:v>${xmlEsc(v)}</c:v></c:pt>`).join('')
    return `${pre}<c:ptCount val="${values.length}"/>${pts}${post}`
  })
}

function setNumCache(chartXml: string, values: number[]): string {
  return chartXml.replace(/(<c:val><c:numRef><c:f>[^<]*<\/c:f><c:numCache>)(.*?)(<\/c:numCache>)/s, (_m, pre: string, body: string, post: string) => {
    const fmt = (body.match(/<c:formatCode>.*?<\/c:formatCode>/) || ['<c:formatCode>General</c:formatCode>'])[0]
    const pts = values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join('')
    return `${pre}${fmt}<c:ptCount val="${values.length}"/>${pts}${post}`
  })
}

// The pie chart's series already carries one <c:dPt> per category (Excel's
// own default "vary colors by point" for a plain pie) using THEME colors
// (accent1, accent2, ...), which vary by slice POSITION, not identity — so
// CDSP wouldn't reliably be the same color across different program
// selections. Replace the whole <c:dPt> list (whatever its current count)
// with one explicit-hex <c:dPt> per selected program, keyed by name.
function setPieColors(chartXml: string, programs: string[]): string {
  const dPts = programs
    .map((name, i) => {
      const color = (GENERAL_PESO_PROGRAM_COLORS[name] || '#94A3B8').replace('#', '')
      return `<c:dPt><c:idx val="${i}"/><c:bubble3D val="0"/><c:spPr><a:solidFill><a:srgbClr val="${color}"/></a:solidFill></c:spPr></c:dPt>`
    })
    .join('')
  return chartXml.replace(/(<\/c:tx>).*?(<c:cat>)/s, `$1${dPts}$2`)
}

// The bar chart's single series fill defaults to the theme's accent1 — force
// it to the app's brand blue so it matches the on-screen/PDF bar chart.
function setBarColor(chartXml: string): string {
  return chartXml.replace('<a:solidFill><a:schemeClr val="accent1"/></a:solidFill>', '<a:solidFill><a:srgbClr val="0077BE"/></a:solidFill>')
}

export async function generateGeneralPesoWorkbook(
  programs: GeneralPesoProgramRow[],
  analytics: { total: number; male: number; female: number },
  periodDetails: string,
  fileName: string,
) {
  const n = programs.length
  const lastRow = 1 + n
  const names = programs.map(p => p.program)
  const counts = programs.map(p => p.participants)

  const buf = await (await fetch(templateUrl)).arrayBuffer()
  const zip = await JSZip.loadAsync(buf)

  // ── ChartData: write the selected programs into rows 2..(1+n), blank the rest ──
  let chartData = await zip.file(SHEET_CHARTDATA)!.async('string')
  for (let i = 0; i < MAX_PROGRAMS; i++) {
    const row = 2 + i
    if (i < n) {
      chartData = setCell(chartData, `A${row}`, programs[i].program, false)
      chartData = setCell(chartData, `B${row}`, programs[i].participants, true)
    } else {
      chartData = setCell(chartData, `A${row}`, '', false)
      chartData = setCell(chartData, `B${row}`, 0, true)
    }
  }
  zip.file(SHEET_CHARTDATA, chartData)

  // ── Charts: shrink the range AND rebuild the cached values to match ──
  let bar = await zip.file(CHART_BAR)!.async('string')
  bar = setChartRange(bar, lastRow)
  bar = setStrCache(bar, names)
  bar = setNumCache(bar, counts)
  bar = setBarColor(bar)
  zip.file(CHART_BAR, bar)

  let pie = await zip.file(CHART_PIE)!.async('string')
  pie = setChartRange(pie, lastRow)
  pie = setStrCache(pie, names)
  pie = setNumCache(pie, counts)
  pie = setPieColors(pie, names)
  zip.file(CHART_PIE, pie)

  // ── Report sheet: period + headline stats ──
  let report = await zip.file(SHEET_REPORT)!.async('string')
  report = setCell(report, 'B3', periodDetails, false)
  report = setCell(report, 'B5', analytics.total, true)
  report = setCell(report, 'B6', analytics.male, true)
  report = setCell(report, 'B7', analytics.female, true)
  zip.file(SHEET_REPORT, report)

  // ── Program Details: the same per-program table as the on-screen preview ──
  let details = await zip.file(SHEET_DETAILS)!.async('string')
  const cols = ['A', 'B', 'C', 'D', 'E', 'F'] as const
  for (let i = 0; i < MAX_PROGRAMS; i++) {
    const row = 2 + i
    if (i < n) {
      const p = programs[i]
      details = setCell(details, `A${row}`, p.program, false)
      details = setCell(details, `B${row}`, p.participants, true)
      details = setCell(details, `C${row}`, p.male, true)
      details = setCell(details, `D${row}`, p.female, true)
      details = p.activities === null ? setCell(details, `E${row}`, '-', false) : setCell(details, `E${row}`, p.activities, true)
      details = p.placements === null ? setCell(details, `F${row}`, '-', false) : setCell(details, `F${row}`, p.placements, true)
    } else {
      cols.forEach(c => { details = setCell(details, `${c}${row}`, '', false) })
    }
  }
  zip.file(SHEET_DETAILS, details)

  const out = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
  const url = URL.createObjectURL(out)
  const link = document.createElement('a')
  link.href = url
  link.download = `${fileName}.xlsx`
  link.click()
  URL.revokeObjectURL(url)
}
