// Base URL + endpoint paths for the ePESO backend API.
// Reads VITE_API_BASE from the .env files (falls back to local XAMPP).

export const API_BASE =
  import.meta.env.VITE_API_BASE ?? 'http://localhost/epeso_backend/api'

// Endpoint paths map 1:1 to backend modules/{module}.php -> handle({action}).
export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
  },
  users: {
    list: '/users/list',
    create: '/users/create',
    update: '/users/update',
  },
  locations: {
    provinces: '/locations/provinces',
    cities: '/locations/cities',
    barangaysByCity: '/locations/barangaysByCity',
    allCities: '/locations/allCities',
  },
  employment: {
    listApplicants: '/employment/listApplicants',
    getApplicant: '/employment/getApplicant',
    getApplicantPhoto: '/employment/getApplicantPhoto',
    getApplicantHistory: '/employment/getApplicantHistory',
    createApplicant: '/employment/createApplicant',
    updateApplicant: '/employment/updateApplicant',
    deleteApplicant: '/employment/deleteApplicant',
    listEmployers: '/employment/listEmployers',
    createEmployer: '/employment/createEmployer',
    updateEmployer: '/employment/updateEmployer',
    deleteEmployer: '/employment/deleteEmployer',
    listVacancies: '/employment/listVacancies',
    createVacancy: '/employment/createVacancy',
    updateVacancy: '/employment/updateVacancy',
    toggleVacancyStatus: '/employment/toggleVacancyStatus',
    listReferrals: '/employment/listReferrals',
    createReferral: '/employment/createReferral',
    updateReferralStatus: '/employment/updateReferralStatus',
    checkDuplicateReferral: '/employment/checkDuplicateReferral',
    deleteReferral: '/employment/deleteReferral',
    listPlacements: '/employment/listPlacements',
    updatePlacement: '/employment/updatePlacement',
    updatePlacementStatus: '/employment/updatePlacementStatus',
    listPromotions: '/employment/listPromotions',
    createPromotion: '/employment/createPromotion',
    monthlyReport: '/employment/monthlyReport',
    // Recycle bin (soft-deleted EF records)
    listDeleted: '/employment/listDeleted',
    restoreRecord: '/employment/restoreRecord',
    purgeRecord: '/employment/purgeRecord',
  },
  cdsp: {
    listServices:             '/cdsp/listServices',
    createService:            '/cdsp/createService',
    deleteService:            '/cdsp/deleteService',
    listActivities:           '/cdsp/listActivities',
    createActivity:           '/cdsp/createActivity',
    updateActivity:           '/cdsp/updateActivity',
    updateActivityStatus:     '/cdsp/updateActivityStatus',
    deleteActivity:           '/cdsp/deleteActivity',
    listActivityParticipants: '/cdsp/listActivityParticipants',
    addParticipant:           '/cdsp/addParticipant',
    removeParticipant:        '/cdsp/removeParticipant',
    updateAttendance:         '/cdsp/updateAttendance',
    listProfiles:             '/cdsp/listProfiles',
    getProfile:               '/cdsp/getProfile',
    createProfile:            '/cdsp/createProfile',
    updateProfile:            '/cdsp/updateProfile',
    deleteProfile:            '/cdsp/deleteProfile',
    listDeleted:              '/cdsp/listDeleted',
    restoreRecord:            '/cdsp/restoreRecord',
    purgeRecord:              '/cdsp/purgeRecord',
  },
  gip: {
    listBatches:       '/gip/listBatches',
    createBatch:       '/gip/createBatch',
    updateBatch:       '/gip/updateBatch',
    deleteBatch:       '/gip/deleteBatch',
    updateBatchStatus: '/gip/updateBatchStatus',
    listProfiles:      '/gip/listProfiles',
    getProfile:        '/gip/getProfile',
    createProfile:     '/gip/createProfile',
    updateProfile:     '/gip/updateProfile',
    deleteProfile:     '/gip/deleteProfile',
    assignBatch:       '/gip/assignBatch',
    unassignBatch:     '/gip/unassignBatch',
    listDeleted:       '/gip/listDeleted',
    restoreRecord:     '/gip/restoreRecord',
    purgeRecord:       '/gip/purgeRecord',
  },
  spes: {
    listBatches:       '/spes/listBatches',
    createBatch:       '/spes/createBatch',
    updateBatch:       '/spes/updateBatch',
    deleteBatch:       '/spes/deleteBatch',
    updateBatchStatus: '/spes/updateBatchStatus',
    listProfiles:      '/spes/listProfiles',
    getProfile:        '/spes/getProfile',
    createProfile:     '/spes/createProfile',
    updateProfile:     '/spes/updateProfile',
    deleteProfile:     '/spes/deleteProfile',
    assignBatch:       '/spes/assignBatch',
    unassignBatch:     '/spes/unassignBatch',
    listDeleted:       '/spes/listDeleted',
    restoreRecord:     '/spes/restoreRecord',
    purgeRecord:       '/spes/purgeRecord',
  },
  dilp: {
    listProjects:       '/dilp/listProjects',
    createProject:      '/dilp/createProject',
    updateProject:      '/dilp/updateProject',
    deleteProject:      '/dilp/deleteProject',
    updateProjectStatus:'/dilp/updateProjectStatus',
    listProfiles:       '/dilp/listProfiles',
    getProfile:         '/dilp/getProfile',
    createProfile:      '/dilp/createProfile',
    updateProfile:      '/dilp/updateProfile',
    deleteProfile:      '/dilp/deleteProfile',
    assignProject:      '/dilp/assignProject',
    unassignProject:    '/dilp/unassignProject',
    listDeleted:        '/dilp/listDeleted',
    restoreRecord:      '/dilp/restoreRecord',
    purgeRecord:        '/dilp/purgeRecord',
  },
  tupad: {
    listProjects:       '/tupad/listProjects',
    createProject:      '/tupad/createProject',
    updateProject:      '/tupad/updateProject',
    deleteProject:      '/tupad/deleteProject',
    updateProjectStatus:'/tupad/updateProjectStatus',
    listProfiles:       '/tupad/listProfiles',
    getProfile:         '/tupad/getProfile',
    createProfile:      '/tupad/createProfile',
    updateProfile:      '/tupad/updateProfile',
    deleteProfile:      '/tupad/deleteProfile',
    assignProject:      '/tupad/assignProject',
    unassignProject:    '/tupad/unassignProject',
    listDeleted:        '/tupad/listDeleted',
    restoreRecord:      '/tupad/restoreRecord',
    purgeRecord:        '/tupad/purgeRecord',
  },
  slp: {
    listProjects:       '/slp/listProjects',
    createProject:      '/slp/createProject',
    updateProject:      '/slp/updateProject',
    deleteProject:      '/slp/deleteProject',
    updateProjectStatus:'/slp/updateProjectStatus',
    listProfiles:       '/slp/listProfiles',
    getProfile:         '/slp/getProfile',
    createProfile:      '/slp/createProfile',
    updateProfile:      '/slp/updateProfile',
    deleteProfile:      '/slp/deleteProfile',
    assignProject:      '/slp/assignProject',
    unassignProject:    '/slp/unassignProject',
    listDeleted:        '/slp/listDeleted',
    restoreRecord:      '/slp/restoreRecord',
    purgeRecord:        '/slp/purgeRecord',
  },
  clpep: {
    listInterventions:       '/clpep/listInterventions',
    createIntervention:      '/clpep/createIntervention',
    updateIntervention:      '/clpep/updateIntervention',
    deleteIntervention:      '/clpep/deleteIntervention',
    updateInterventionStatus:'/clpep/updateInterventionStatus',
    listProfiles:            '/clpep/listProfiles',
    getProfile:              '/clpep/getProfile',
    createProfile:           '/clpep/createProfile',
    updateProfile:           '/clpep/updateProfile',
    deleteProfile:           '/clpep/deleteProfile',
    assignIntervention:      '/clpep/assignIntervention',
    unassignIntervention:    '/clpep/unassignIntervention',
    listDeleted:             '/clpep/listDeleted',
    restoreRecord:           '/clpep/restoreRecord',
    purgeRecord:             '/clpep/purgeRecord',
  },
  skillsTraining: {
    listBatches:              '/skills_training/listBatches',
    createBatch:              '/skills_training/createBatch',
    deleteBatch:              '/skills_training/deleteBatch',
    listActivities:           '/skills_training/listActivities',
    createActivity:           '/skills_training/createActivity',
    updateActivity:           '/skills_training/updateActivity',
    updateActivityStatus:     '/skills_training/updateActivityStatus',
    deleteActivity:           '/skills_training/deleteActivity',
    listActivityParticipants: '/skills_training/listActivityParticipants',
    addParticipant:           '/skills_training/addParticipant',
    removeParticipant:        '/skills_training/removeParticipant',
    updateAttendance:         '/skills_training/updateAttendance',
    listQualifications:       '/skills_training/listQualifications',
    listPurposes:             '/skills_training/listPurposes',
    listProfiles:             '/skills_training/listProfiles',
    getProfile:               '/skills_training/getProfile',
    createProfile:            '/skills_training/createProfile',
    updateProfile:            '/skills_training/updateProfile',
    deleteProfile:            '/skills_training/deleteProfile',
    listDeleted:              '/skills_training/listDeleted',
    restoreRecord:            '/skills_training/restoreRecord',
    purgeRecord:              '/skills_training/purgeRecord',
  },
  ofw: {
    listRequestTypes: '/ofw/listRequestTypes',
    listProfiles:     '/ofw/listProfiles',
    getProfile:       '/ofw/getProfile',
    createProfile:    '/ofw/createProfile',
    updateProfile:    '/ofw/updateProfile',
    updateStatus:     '/ofw/updateStatus',
    deleteProfile:    '/ofw/deleteProfile',
    listDeleted:      '/ofw/listDeleted',
    restoreRecord:    '/ofw/restoreRecord',
    purgeRecord:      '/ofw/purgeRecord',
  },
  activityLogs: {
    list: '/activity_logs/list',
  },
  documents: {
    listFolders:    '/documents/listFolders',
    createFolder:   '/documents/createFolder',
    renameFolder:   '/documents/renameFolder',
    deleteFolder:   '/documents/deleteFolder',
    listDocuments:  '/documents/listDocuments',
    uploadDocument: '/documents/uploadDocument',
    renameDocument: '/documents/renameDocument',
    moveDocument:   '/documents/moveDocument',
    deleteDocument: '/documents/deleteDocument',
    listDeleted:    '/documents/listDeleted',
    restoreRecord:  '/documents/restoreRecord',
    purgeRecord:    '/documents/purgeRecord',
  },
  reports: {
    summary: '/reports/summary',
  },
  backup: {
    listBackups:    '/backup/listBackups',
    createBackup:   '/backup/createBackup',
    downloadBackup: '/backup/downloadBackup',
    deleteBackup:   '/backup/deleteBackup',
  },
} as const
