// A complete, empty ApplicantFormData. Used both by the Add Applicant form's
// local state and by bulk import (so importer rows only need to override the
// handful of fields they carry). Kept in its own module so AddApplicantSidebar
// stays a component-only file (React Fast Refresh requirement).

import type { ApplicantFormData } from "./AddApplicantSidebar";

export function createDefaultApplicantFormData(): ApplicantFormData {
  return {
    surname: "",
    firstName: "",
    middleName: "",
    suffix: "",
    dateOfBirth: "",
    sex: "",
    religion: "",
    civilStatus: "",
    height: "",
    houseNo: "",
    barangay: "",
    barangayId: null,
    municipality: "",
    cityId: null,
    province: "",
    provinceId: null,
    hasDisability: [],
    disabilityOther: "",
    tin: "",
    contactNumber: "",
    email: "",
    isOFW: "No",
    ofwCountry: "",
    isFormerOFW: "No",
    formerOFWCountry: "",
    formerOFWReturnDate: "",
    is4PsBeneficiary: "No",
    householdIdNo: "",
    employmentStatus: "",
    employmentType: "",
    selfEmploymentType: "",
    selfEmploymentOther: "",
    unemploymentReason: "",
    unemploymentReasonOther: "",
    monthsLookingForWork: "",
    jobPrefEmploymentType: [],
    jobPrefWorkLocation: [],
    jobPreferences: [
      { occupation: "", localCity: "", overseasCountry: "" },
      { occupation: "", localCity: "", overseasCountry: "" },
      { occupation: "", localCity: "", overseasCountry: "" },
    ],
    languages: [
      { language: "ENGLISH", read: false, write: false, speak: false, understand: false },
      { language: "FILIPINO", read: false, write: false, speak: false, understand: false },
      { language: "MANDARIN", read: false, write: false, speak: false, understand: false },
    ],
    currentlyInSchool: "",
    elementary: { schoolName: "", schoolCity: "", schoolProvince: "", graduated: "", yearGraduated: "", levelReached: "", yearLastAttended: "" },
    secondary: { schoolName: "", schoolCity: "", schoolProvince: "", type: "", seniorHighStrand: "", graduated: "", yearGraduated: "", levelReached: "", yearLastAttended: "" },
    tertiary: { schoolName: "", schoolCity: "", schoolProvince: "", course: "", graduated: "", yearGraduated: "", levelReached: "", yearLastAttended: "" },
    graduateStudies: [],
    trainings: [],
    eligibilities: [],
    professionalLicenses: [],
    workExperiences: [],
    otherSkills: [],
    otherSkillsSpecify: [""],
    referredProgram: "",
    referredProgramOther: "",
    cdspPrograms: [],
    livelihoodPrograms: [],
    dileepPrograms: [],
    projectIdNumber: "",
    projectLocation: "",
    projectRegion: "",
    projectCity: "",
    projectDetails: { type: [], programComponent: [], wayOfImplementation: [], nameOfProject: "" },
    pagIbigNo: "",
    philHealthNo: "",
    sssNo: "",
    otherProgramName: "",
    otherProgramNo: "",
    documentType: "",
    documentOtherSpecify: "",
    savedDocuments: [],
  };
}
